/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zkmsegawmokujifugpwm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbXNlZ2F3bW9rdWppZnVncHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzA2ODgsImV4cCI6MjA3NDkwNjY4OH0.ez9BUoBCJXIunH2T7Xt-4n_tu4DCaQ_0-t7Ps8ivb0c"